## Spring boot config
spring.web.resources.add-mappings=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ===============================
# Database (H2 file-based)
# ===============================
#spring.datasource.url=jdbc:h2:mem:recipesdb
spring.datasource.url=jdbc:h2:file:./data/recipesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Schema management
spring.jpa.hibernate.ddl-auto=update
# ===============================
# H2 Console (dev only)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# Logging
# ===============================
logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.nl.inholland.recipekeeper=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
#DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF 
# TRACE

# ===============================
# JPA / Hibernate tuning
# ===============================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================
server.port=8080
server.shutdown=graceful

# ===============================
# External API
# ===============================
# API key
mealdb.api.key=${THEMEALDB_API_KEY:1}

# Base API
mealdb.api.base=https://www.themealdb.com/api/json/v1/${mealdb.api.key}

# Search
mealdb.api.search=${mealdb.api.base}/search.php?s={meal_name}
mealdb.api.lookup=${mealdb.api.base}/lookup.php?i={meal_id}
mealdb.api.random=${mealdb.api.base}/random.php

# Catalogs
mealdb.api.categories=${mealdb.api.base}/list.php?c=list
mealdb.api.areas=${mealdb.api.base}/list.php?a=list

# Filters
mealdb.api.filter.category=${mealdb.api.base}/filter.php?c={category}
mealdb.api.filter.area=${mealdb.api.base}/filter.php?a={area}
mealdb.api.filter.ingredient=${mealdb.api.base}/filter.php?i={ingredient}

# Images
mealdb.api.image.meal={strMealThumb}
mealdb.api.image.ingredient.small=https://www.themealdb.com/images/ingredients/{ingredient}-small.png
mealdb.api.image.ingredient.medium=https://www.themealdb.com/images/ingredients/{ingredient}-medium.png
mealdb.api.image.ingredient.large=https://www.themealdb.com/images/ingredients/{ingredient}-large.png